# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Juvenal A. Silva Jr.
email: contact@juvenaljr.com
description: > # this means to ignore newlines until "baseurl:"
  The clashing of tech, science, philosophy and art.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.juvenaljr.com" # the base hostname & protocol for your site
twitter_username: juvenal_silva
github_username:  juvenal
permalink: pretty

# Build settings
markdown: kramdown

## Configuration options
timezone: America/Sao_Paulo
#source:      _source
#destination: _deploy

# Install jekyll plugins
gems:
- jekyll-language-plugin
