# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juvenal's disclosures
title_image: '/assets/images/title_image.svg'
email: contact@juvenal.me
description: > # this means to ignore newlines until "baseurl:"
  Those are some of my personal ruminations...
#  The clashing of tech, science, art and lifestyle, as I see it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: juvenal_silva
github_username: juvenal
linkedin_username: juvenalsilva
google_analytics_id: UA-370154-5
aweber_analytics_id: 1ZT.U
author_name: 'Juvenal A. Silva Jr.'
author_email: 'contact@juvenal.me'
permalink: pretty
excerpt_separator: <!--more-->

# Discus comments configuration
disqus:
  shortname: juvenaljr

## Configuration options
timezone: America/Sao_Paulo

# Build settings
markdown: kramdown

# Mermaid settings
mermaid:
  src: '/assets/scripts/mermaid.min.js'
  src_config: '/assets/scripts/mermaid_config.js'

# Graphviz settings
graphviz:
  options: "-Tsvg"
  executable: "dot"

# Diagrams settings
#diagrams:
#  graphviz:
#    engine: dot
#    options: '-Tsvg'
#  diag:
#    options: '-Tsvg --nodoctype'

# Pagination Settings
#pagination:
#  enabled: true
#  per_page: 5
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-mermaid
  - jekyll-pseudocode-b
#  - jekyll-graphviz
#  - jekyll-diagrams

exclude:
  - Gemfile
  - Gemfile.lock

